# Generated by Django 4.0.1 on 2022-03-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('otp_field', models.CharField(max_length=6)),
                ('created_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
